on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rasmus-saks/release-a-changelog-action@v1.0.1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'

  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: cksfv
          token: ${{ secrets.GITHUB_TOKEN }}
          checksum: sha256
          include: CHANGELOG.md,COPYING,README.md
